[".oh-my-zsh"]
type = "archive"
url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
type = "archive"
url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
type = "archive"
url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"
[".zsh/_git"]
type = "file"
url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh"
refreshPeriod = "168h"
[".zsh/git-completion.bash"]
type = "file"
url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash"
refreshPeriod = "168h"
[".zsh/git-prompt.sh"]
type = "file"
url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
refreshPeriod = "168h"
[".zsh/tabtab-pnpm.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/denosaurs/tabtab/main/scripts/zsh.sh"
refreshPeriod = "168h"