onboarding = false

[ui.sound]
# sounds/request-voidoll.mp3: VOICEVOX:Voidoll(CV:丹下桜)（「質問があります」）
# sounds/complete-voidoll.mp3: VOICEVOX:Voidoll(CV:丹下桜)（「作業が終わりました」）
request_path = "sounds/request-voidoll.mp3"
done_path = "sounds/complete-voidoll.mp3"
